services:
  manager:
#    tty: true
    build:
      context: .
      dockerfile: manager/Dockerfile
    hostname: manager
    container_name: manager
    networks:
      - rfswarm
    volumes:
      - ./reports:/src/reports
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./tests:/src/tests
    ports:
      - "8138:8138"
    environment:
      - DISPLAY=$DISPLAY 

  firefox_agent:
    build:
      context: .
      dockerfile: agent/seleniumlibrary-firefox/Dockerfile
    hostname: agent
    container_name: agent
    networks:
      - rfswarm   

networks:
  rfswarm: