services:
  rfswarm_agent_selenium-ff:
    build:
      context: agent
      dockerfile: seleniumlibrary-firefox/Dockerfile
    hostname: agent_selenium-firefox    
    container_name: agent_selenium-firefox
    volumes:
      - ./tests:/src/product/tests
      - /tmp/.X11-unix:/tmp/.X11-unix
    entrypoint: tail -f /dev/null  
