services:
  rfswarm_agent:
    build:
      context: .
      dockerfile: agent/rfswarm-base-image/Dockerfile
    hostname: rfswarm_agent    
    container_name: rfswarm_agent
    ports:
      - "8138:8138"
    volumes:
      - type: bind
        source: agent/rfswarm-base-image/entrypoint.sh
        target: /opt/bin/entrypoint.sh
