services:
  rfswarm_agent_selenium:
    build:
      context: agent
      dockerfile: seleniumlibrary-chrome/Dockerfile
    hostname: agent_selenium-chrome    
    container_name: agent_selenium-chrome
    volumes:
      - ./tests:/src/product/tests
