services:
  rfswarm_agent:
    build:
      context: agent
      dockerfile: distribution/base/Dockerfile
    image: ghcr.io/Esthenia-collaboration/rfswarm-base-image:latest  
    hostname: rfswarm_agent    
    container_name: rfswarm_agent
    ports:
      - "8138:8138"

  
  
