services:
  manager:
#    tty: true
    build:
      context: .
      dockerfile: manager/Dockerfile
    hostname: manager
    container_name: manager
    networks:
      - rfswarm
    volumes:
      - ./reports:/src/reports
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./tests/suites:/src/tests
    ports:
      - "8138:8138"
      - "2222:22"
    environment:
      - DISPLAY=$DISPLAY 

  ssh_agent:
    build:
      context: .
      dockerfile: agent/sshlibrary/Dockerfile
    hostname: agent
    container_name: agent
    networks:
      - rfswarm   

networks:
  rfswarm: