---
name: Check Docker Can Compose

on: push

jobs:
  Check_Compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check that the image pulls and runs
        run: docker compose up -d
      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash
      - name: Shut docker down
        run: docker compose down
