name: Publish docker sshlibrary agent image on dockerhub
on:
  push:

env:
  DOCKER_IMAGE_NAME: estheniacollaboration/agents/rfswarm-sshlibrary
  DOCKER_IMAGE_TAG: 1.0.0

jobs:
  check_docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check that the image builds
        run: docker build -t rfswarm-sshlibrary-for-check -f agent/rfswarm-sshlibrary/Dockerfile .
      - name: Check that the built image runs
        run: docker run -d --rm --name rfswarm-sshlibrary-container-for-check rfswarm-sshlibrary-for-check
      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash
      - name: Shut docker container stop
        run: docker stop rfswarm-sshlibrary-container-for-check
  push_to_dockerhub_registry:
    name: Push rfswarm-agent-sshlibrary docker image to dockerhub registry
    needs: check_docker_build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to DockerHub Container Registry with secret variables
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the rfswarm agent sshlibrary docker image
        run: docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG -f agent/rfswarm-sshlibrary/Dockerfile .
      - name: Push image on dockerhub registry
        run: docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
