name: Publish docker image pipeline
on:
  push:

env:
  DOCKER_IMAGE_NAME: estheniacollaboration/agents/rfswarm-agent-base-image
  DOCKER_IMAGE_TAG: latest

jobs:
  check_docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check that the image builds
        run: docker build -t rfswarm-base-image-for-check -f agent/rfswarm-base-image/Dockerfile .
      - name: Check that the built image runs
        run: docker run -d --rm --name rfswarm-base-container-for-check rfswarm-base-image-for-check
      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash
      - name: Shut docker container stop
        run: docker stop rfswarm-base-container-for-check
  push_to_dockerhub_registry:
    name: Push rfswarm-agent docker base image to dockerhub registry
    needs: check_docker_build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to DockerHub Container Registry with secret variables
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the rfswarm agent docker base image
        run: docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG -f agent/rfswarm-base-image/Dockerfile .
      - name: Push image on dockerhub registry
        run: docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
#  check_compose:
#    runs-on: ubuntu-latest
#    needs: push_to_github_registry
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#      - name: Check that the image builds and runs
#        run: docker compose up -d
#      - name: Sleep for 30 seconds
#        run: sleep 30s
#        shell: bash
#      - name: Shut docker down
#        run: docker compose down