name: Standard any branch CI workflow

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  check_build_push:
    if: github.ref_type == 'tag'
    uses: ./.github/workflows/check_build_push_template.yml
    with:
      REGISTRY_URL: docker.io
      DOCKER_IMAGE_PREFIX: /estheniacollaboration/rfswarm-
      DOCKER_IMAGE_TAG: ${{ github.ref_name }}
    secrets:
      REGISTRY_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
