name: publish rfswarm base image on github container registry
on: [push]
jobs:
  run-rfswarm-image-from-gcr:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
    uses: docker/login-action@v1
    with:
    registry: rfswarm-gcr.io
    username: ${{ github.actor }}
    password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the rfswarm docker base image
    run: |
          docker build . --tag rfswarm-gcr.io/deselikem/hello-docker-gcr-demo:latest
          docker run rfswarm-gcr.io/rfswarm/hello-docker-gcr-demo:latest
          docker push rfswarm-gcr.io/rfswarm/hello-docker-gcr-demo:latest