name: Test workflow
on:
  push:
    branches-ignore:
      - main
#    paths:
#      - 'agent/base/**'
#      - 'agent/with-ssh/**'

jobs:
  check_docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Show variables
        run: |
          ORIGINAL_PATH="${{ github.event_path }}"
          NEW_PATH="${ github.event_path////- }"
          echo "Original path: ${ORIGINAL_PATH}"
          echo "New path: ${NEW_PATH}"
